openapi: 3.0.0
info:
  version: "1.0.0"
  title: StripeSubscriptionService
  description: A service for managing Stripe subscriptions.
servers:
- url: http://localhost:2132
paths:
 /register:
    post:
      summary: Register a new user.
      description: Register a new user.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                fullName:
                  type: string
                emailId:
                  type: string
                password:
                  type: string
                countryCode:
                  type: string
                contactNumber:
                  type: string
              required:
              - fullName
              - emailId
              - password
              - countryCode
              - contactNumber
      responses:
        200:
          description: Registration successful.
        409:
          description: User already registered or validation error.
        500:
          description: Internal Server Error.

 /login:
    post:
      summary: Authenticate a user and return a token.
      description: Authenticate a user and return a token.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                emailId:
                  type: string
                password:
                  type: string
              required:
              - emailId
              - password
      responses:
        200:
          description: Login success.
        400:
          description: Invalid email or password.
        409:
          description: Empty values.
        500:
          description: Internal Server Error.

 /productsDetail:
    get:
      summary: Get All Subscription plan from Stripe.
      description: Get All Subscription plan from Stripe.
      responses:
        200:
          description: Success.
        500:
          description: Failed to fetch products.
      security:
      - BearerAuth: []

 /subscribe:
  post:
    summary: Create a new subscription for a user.
    description: Create a new subscription for a user with the specified productId.
    requestBody:
      required: true
      content:
        application/json:
          schema:
            type: object
             properties:
               productId:
                  type: string
                  description: Subscription productId
            required:
            - productId
    responses:
      200:
        description: Subscription session URL.
        content:
          application/json:
            schema:
              type: object
              properties:
                status:
                  type: string
                  example: "success"
      400:
        description: Missing required fields.
      404:
        description: Product not found or inactive.
      500:
        description: Error creating subscription.
    security:
    - BearerAuth: []

 /userDetailAndSubscriptionHistory:
    get:
      summary: Retrieve user and subscription details and update old data status into active to inactive.
      description: Retrieve user and subscription details and update the status of old subscriptions.
      responses:
        200:
          description: User and Subscription Details.
        400:
          description: User not found.
        500:
          description: Internal Server Error.
      security:
      - BearerAuth: []

 /logout:
    post:
      summary: Logout the user and clear the token in the database.
      description: Logout the user and clear the token in the database.
      responses:
        200:
          description: Logout successful.
        404:
          description: User not found.
        500:
          description: Internal Server Error.
      security:
      - BearerAuth: []

 /customers:
    post:
      summary: Upgrade and downgrade the subscription using the Stripe customer portal.
      description: Access the Stripe customer portal for managing subscription upgrades or downgrades.
      responses:
        200:
          description: Success.
        500:
          description: Internal Server Error.
      security:
      - BearerAuth: []

 components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT # Optional: indicates that the format is JWT (JSON Web Token)

  schemas:
    User:
      type: object
      properties:
        fullName:
          type: string
        email:
          type: string
        password:
          type: string
        contactNumber:
          type: string
        countryCode:
          type: string
        customerStripeId:
          type: string
        token:
          type: string
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time

    Subscription:
      type: object
      properties:
        customerId:
          type: string
        productId:
          type: string
        priceId:
          type: string
        subscriptionId:
          type: string
        planName:
          type: string
        amount:
          type: number
        currency:
          type: string
        interval:
          type: string
        intervalCount:
          type: integer
        status:
          type: string
        startDate:
          type: string
          format: date-time
        endDate:
          type: string
          format: date-time
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
